### ISSUE TITLE
Female sprites aren't working

### ISSUE THREAD

**Issue by turbedi** [po-devs/po-web#198]
Only the male sprites are shown in teambuilder and in a battle

**Comment by coyotte508** [comment]
Yea.

Two solutions: 
- copy over all sprites to female/
- run a script to gather which poke have a female sprite, put that in a db file

**Comment by coyotte508** [comment]
Actually, I could change the web server so that in case of missing file it tries the regular version of a sprite. Would have to do it first for the server of the webclient, and second for pokemon-online.eu (actually could even run the webclient on pokemon-online.eu)

**Comment by turbedi** [comment]
Isn't it possible to check if the pokemon is female and if that's the case, try to load the sprite from female/ and if there is no sprite, default back to the regular one.
And doesn't [this](https://github.com/po-devs/po-web/blob/bf00719804738594954d83fa8d4dd662bbaa32f0/app/assets/javascript/frontend.js#L346) already load the regular sprite in case of a missing file?

**Comment by coyotte508** [comment]
It does, but it's not the most efficient for sprites in teambuilder and battle, one request should be enough.

It's better to server directly the correct sprite, `server.js` can be edited to do that. And since I moved webclient to the site's server, it'll also work with animated sprite. Anyway this is coming soon, don't worry!
